name: Lint
# Lint runs golangci-lint over the entire repository
# This workflow is run on every pull request and push to main
# The `golangci` will pass without running if no *.{go, mod, sum} files have been changed.

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

# concurrency:
#   group: ci-${{ github.ref }}-lint
#   # cancel-in-progress: true

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.51.1
          args: --timeout 20m0s
