name: Sims
# Sims workflow runs multiple types of simulations (nondeterminism, import-export, after-import, multi-seed-short)
# This workflow will run on all Pull Requests, if a .go, .mod or .sum file have been changed
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}-sims
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-sims')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - run: make -C simapp build

  # install-runsim:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: "1.21"
  #     - name: Display go version
  #       run: go version
  #     - name: Install runsim
  #       run: export GO111MODULE="on" && go install github.com/cosmos/tools/cmd/runsim@v1.0.0
  #     - name: Add Go bin to PATH
  #       run: echo "${HOME}/go/bin" >> $GITHUB_PATH  # This adds the Go bin directory to PATH
  #     - uses: actions/cache@v3.0.8
  #       with:
  #         path: ~/go/bin
  #         key: ${{ runner.os }}-go-runsim-binary

  install-runsim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Display go version
        run: go version
      - name: Install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@v1.0.0
      - name: Add Go bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH  # This adds Go bin to PATH for subsequent steps
      - name: Verify runsim installation
        run: runsim --help

  test-sim-nondeterminism:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: test-sim-import-export
        run: |
          make test-sim-nondeterminism

  test-sim-import-export:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: Add Go bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH
      - name: test-sim-import-export
        run: |
          ${HOME}/go/bin/runsim --help 
          make test-sim-import-export

  test-sim-after-import:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: Add Go bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH
      - name: test-sim-after-import
        run: |
          make test-sim-after-import

  test-sim-multi-seed-short:
    runs-on: ubuntu-latest
    needs: [build]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: Add Go bin to PATH
        run: echo "${HOME}/go/bin" >> $GITHUB_PATH
      - name: test-sim-multi-seed-short
        run: |
          make test-sim-multi-seed-short
